config/routes.rb
Rails.application.routes.draw do
  scope "checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  resources :details
  resources :products
  resources :sizes
  resources :categories
  resources :photographers
  resources :order_details

  resources :customers, only: %i[create show index]
  post "/login", to: "auth#login"
  get "/auto_login", to: "auth#auto_login"
  get "/user_is_authed", to: "auth#user_is_authed"

  resources :taxes
  resources :provinces
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :description, presence: true
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password :password
  validates :first_name, :last_name, :email, :address, :phone_number, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, uniqueness: { case_sensitive: false }
  has_one_attached :cust_image

  has_many :order_details
  belongs_to :province
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :order_detail
  belongs_to :product
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  validates :reference_number, :total, :historical_tax, presence: true
  validates :historical_tax, :total, numericality: { greater_than_or_equal_to: 0.00, allow_blank: true }

  belongs_to :customer

  has_many :details
  has_many :products, through: :details
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  validates :full_name, :description, presence: true
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.00, allow_blank: true }
  has_one_attached :prod_image

  belongs_to :photographer
  belongs_to :category
  has_and_belongs_to_many :sizes

  has_many :details
  has_many :order_details, through: :details
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
  has_many :taxes
  has_many :customers
end

app/models/scraper.rb
require "nokogiri"
require "httparty"
require "byebug"

class Scraper
  def scrape_photographers
    photographer_url = "https://www.pocket-lint.com/apps/news/instagram/131470-incredible-photographers-to-follow-on-instagram-right-now"
    # The HTTParty method takes in our URL string, and returns the HTML from that page.
    unparsed = HTTParty.get(photographer_url)
    # Nokogiri's HTML method then takes in our html arguement, and returns to us a set of nodes
    parsed = Nokogiri::HTML(unparsed)

    photographers = []
    photographer_listings = parsed.css(".text-content").css(".nolinks2")
    photographer_descriptions = parsed.css(".text-content").css("p")
    photographer_listings.each.with_index do |photographer_listing, index|
      photographer = {
        name:        photographer_listing.text,
        description: photographer_descriptions[index + 4].text
      }

      photographers << photographer
    end

    photographers
  end

  def scrape_taxes_by_province
    taxes_url = "http://www.calculconversion.com/sales-tax-calculator-hst-gst.html"
    unparsed = HTTParty.get(taxes_url)
    parsed = Nokogiri::HTML(unparsed)

    taxes = []
    tax_listings = parsed.css(".text_calcul").css("table").css("tr")
    tax_listings.each.with_index do |tax_listing, index|
      if index != 0
        tax_by_province = {
          province:  tax_listing.css("th").text,
          tax_names: tax_listing.css("td")[0].text.split("+"),
          prov_tax:  tax_listing.css("td")[1].text.strip.sub("%", "").to_i,
          govt_tax:  tax_listing.css("td")[2].text.strip.sub("%", "").to_i
        }

        taxes << tax_by_province
      end
    end

    taxes
  end

  def scrape_categories
    categories_url = "https://www.stocksy.com/blog/types-of-photography/"
    unparsed = HTTParty.get(categories_url)
    parsed = Nokogiri::HTML(unparsed)

    categories = []
    category_listings = parsed.css("div.col-md-6").css("div.margin-bottom-lg:not(.image-block)")
    category_listings.each.with_index do |category_listing, index|
      if index != 0 && index != (category_listings.count - 1)
        category = {
          name:        category_listing.css("h3").text,
          description: category_listing.css("p")[0].text
        }
        categories << category
      end
    end

    categories
  end
end

app/models/size.rb
class Size < ApplicationRecord
  validates :name, :size, presence: true
  has_and_belongs_to_many :products
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :name, :tax, presence: true
  belongs_to :province
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_format
  before_action :set_detail, only: %i[show edit update destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.includes(:order_detail, :product).all
  end

  # GET /details/1
  # GET /details/1.json
  def show; end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit; end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: "Detail was successfully created." }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: "Detail was successfully updated." }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: "Detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Format to json
  def set_format
    request.format = :json
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_detail
    @detail = Detail.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def detail_params
    params.require(:detail).permit(:price, :quantity, :order_detail_id, :product_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/details/_form.html.erb
<%= form_with(model: detail, local: true) do |form| %>
  <% if detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :order_detail_id %>
    <%= form.text_field :order_detail_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Details</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Quantity</th>
      <th>Order detail</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.price %></td>
        <td><%= detail.quantity %></td>
        <td><%= detail.order_detail_id %></td>
        <td><%= detail.product_id %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @detail.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @detail.quantity %>
</p>

<p>
  <strong>Order detail:</strong>
  <%= @detail.order_detail_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @detail.product_id %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>